### ISSUE TITLE
Raviewer on Dear PyGui showcase

### ISSUE THREAD

**Issue by bandit-masked** [antmicro/raviewer#1]
Hi,

I noticed that you used Dear PyGui as your GUI for Raviewer. Raviewer looks like it could make a nice example app on the Dear PyGui Showcase (https://github.com/hoffstadt/DearPyGui/wiki/Dear-PyGui-Showcase).

Would you be willing to make a video or GIF that demonstrates the GUI interface and process so that it can be embedded on that page?

Thank you!

**Comment by bandit-masked** [comment]
In addition, it seems that you have updated the app to work with Dear PyGui 1.x, but the readme still refers to dearpygui == 0.8.64.

**Comment by tmichalak** [comment]
Hi @bandit-masked, we updated the README, so thanks for pointing this out.
The DearPyGui Showcase is an interesting idea, we will definitely work on creating one. Thanks!!!

**Comment by bandit-masked** [comment]
That would be great. Looking forward to it!

Note that the maximum file size is about 10Mb on GitHub.

**Comment by bandit-masked** [comment]
I'd also like to create a series of videos of Dear PyGui apps on YouTube. So, if you could create a longer (1 - 5 minutes, depending on how much there is to show) video that can be uploaded, that would be great!

**Comment by bandit-masked** [comment]
Just wanted to let you know that I have made a GIF and listed RaViewer on the Dear PyGui showcase page.
https://github.com/hoffstadt/DearPyGui/wiki/Dear-PyGui-Showcase

The app looks great and a good match for DPG.

**Comment by tmichalak** [comment]
Thanks @bandit-masked. In case we wanted to make some adjustments to your description is there a process for updating the DPG Showcase page or can I just update the document?

**Comment by tmichalak** [comment]
@bandit-masked 
> I'd also like to create a series of videos of Dear PyGui apps on YouTube. So, if you could create a longer (1 - 5 minutes, depending on how much there is to show) video that can be uploaded, that would be great!

Are there any limitations with regard to this video (size, format) ?

**Comment by bandit-masked** [comment]
> Thanks @bandit-masked. In case we wanted to make some adjustments to your description is there a process for updating the DPG Showcase page or can I just update the document?

It's an open wiki, so you can edit the description yourself. Kindly keep it in line with the other items. Other than that, feel free to improve it.

**Comment by bandit-masked** [comment]
> Are there any limitations with regard to this video (size, format) ?

I was thinking of a 1920x1080 video, app in full screen mode or at least a neutral desktop as background. The length of the video would depend on how much functionality you want and can show. You can include some background information and explain what is happening with a voice over or not. It's up to you. I haven't done any other videos yet.

**Comment by bandit-masked** [comment]
I posted the GIF on r/dearpygui as well and it seems people like it.
https://www.reddit.com/r/DearPyGui/comments/tiwwf0/raviewer_parsing_and_displaying_binary_data/

**Comment by albfan** [comment]
Is this issue completed?

**Comment by bandit-masked** [comment]
Yes!

**Comment by albfan** [comment]
Cool, so, why not close it?
